sm7250-common: remove ndk_platform backend. use the ndk backend
The ndk_platform backend will soon be deprecated because the ndk backend
can serve the same purpose. This is to eliminate the confusion about
having two variants (ndk and ndk_platform) for the same ndk backend.

Bug: 161456198
Test: m
Merged-In: I14a1c57bd06f1f2aa52491f779c7030d4de03547
Change-Id: I7b9055909b901843631314b9577a9e578a739d00

error: device/xiaomi/sm7250-common/lights/Android.bp:1:1: "android.hardware.lights-service.xiaomi_lito" depends on undefined module "android.hardware.light-V1-ndk_platform"
error: device/xiaomi/sm7250-common/vibrator/Android.bp:4:1: "vendor.qti.hardware.vibrator.impl.xiaomi_lito" depends on undefined module "android.hardware.vibrator-V1-ndk_platform"